config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks, only: [:new, :create, :update, :edit]
  end

  resources :tasks, only: [:destroy, :show, :index]
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  attribute :complete, :boolean, default: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @list = List.new
  end

  def edit
    @list = find_current_list
  end

  def show
    @list = find_current_list
  end

  def update
    @list = find_current_list
    if @list.update(list_params)
      redirect_to list_path(find_current_list)
    else
      render :update
    end
  end

  def destroy
    @list = find_current_list
    @list.destroy
    redirect_to root_path
  end

  private

  def find_current_list
    List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def create
    @list = current_list
    @task = Task.new(task_params)
    @task.list_id = @list.id
    if @task.save
      redirect_to list_path(@list)
    else
      flash[:error] = 'Failed to create'
      redirect_to new_list_task_path(@list)
    end
  end

  def show
    @task = current_task
    @list = @task.list
  end

  def new
    @list = current_list
    @task = Task.new
  end

  def update
    @task = current_task
    @list = @task.list
    if @task.update(task_params)
      redirect_to list_path(@list)
    else
      flash[:error] = 'Failed to update'
      redirect_to edit_list_task_path(@list, @task)
    end
  end

  def edit
    @task = current_task
    @list = @task.list
  end

  def destroy
    @task = current_task
    @list = @task.list
    @task.destroy
    redirect_to list_path(@list)
  end

  def update_completion
    @task_ids = params[:task_ids]
    Task.where(id: @task_ids).update_all(complete: true)

    @list = current_list
    redirect_to list_path(@list)
  end

  private

  def current_task
    Task.find(params[:id])
  end

  def current_list
    List.find(params[:list_id])
  end

  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheckList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: @list, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, id: :list_title, required: true %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h2>Edit List</h2>

<p><%= render 'form', list: @list %></p>

app/views/lists/index.html.erb
<h2>Check Lists</h2>

<p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
    <tr>
      <td><%= list.title %></td>
      <td><%= link_to 'Show', list_path(list) %></td>
      <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</p>

<p><%= link_to 'New List', new_list_path %></p>

app/views/lists/new.html.erb
<h2>Create New List</h2>

<p><%= render 'form', list: @list %></p>

<p><%= link_to 'Back', root_path %></p>

app/views/lists/show.html.erb
<h2><%= @list.title %></h2>
<%= link_to "Edit", edit_list_path(@list) %>

<p>
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Complete</th>
      </tr>
    </thead>

    <tbody>
      <% @list.tasks.each do |task| %>
        <tr>
          <td><%= task.description %></td>
          <td><%= check_box_tag "complete", task.id %></td>
          <td><%= link_to "Edit", edit_list_task_path(@list, task) %> </td>
          <td><%= link_to "Delete", task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<p><%= link_to 'Add Task', new_list_task_path(@list) %></p>
<p><%= link_to 'Back', root_path %></p>

app/views/tasks/_form.html.erb
<%= form_with(model: [@list, @task], local: true) do |form| %>
  <div class="field">
    <%= form.label :description %>
    <br>
    <%= form.text_field :description, id: :task_description %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<p><%= render 'form', task: @task %></p>

<p><%= link_to 'Back', list_path(@list) %></p>

app/views/tasks/new.html.erb
<h2>Add A New Task</h2>

<p><%= render 'form', task: @task %></p>

<p><%= link_to 'Back', list_path(@list) %></p>